### ISSUE TITLE
Error al cargar Recibo de Cliente

### ISSUE THREAD

**Issue by juandanielp24** [ctmil/odoo-argentina#13]
> **Error al cargar Recibo de Cliente:**
>
> account.payment.group(8,).company_regimenes_ganancias_ids
>
> *Version afectada:*
> 
>  - 13.0
> 
> *Pasos para reproducir:*
> 
>  1. Crear un "Recibo de Cliente"
>  2. Tanto si el cliente seleccionado tiene una FC cargada como si no da el error al querer guardar o validar. Los botones quedan "deshabilitados" y hay que refrescar para que el sistema responda.
>  3. Si vamos a "Pagos" veremos que el pago generado antes queda en Borrador.
>  4. En "Recibos de Cliente" no podemos ingresar al recibo dado que da el error nuevamente.

![image](https://user-images.githubusercontent.com/62858972/79994117-f0977600-848b-11ea-960e-eb04080eb827.png)

**Comment by MatiasJAco** [comment]
We are having  the same problem. Hope this gets checked.

**Comment by azurita** [comment]
> > **Error al cargar Recibo de Cliente:**
> > account.payment.group(8,).company_regimenes_ganancias_ids
> > _Version afectada:_
> > 
> > * 13.0
> > 
> > _Pasos para reproducir:_
> > 
> > 1. Crear un "Recibo de Cliente"
> > 2. Tanto si el cliente seleccionado tiene una FC cargada como si no da el error al querer guardar o validar. Los botones quedan "deshabilitados" y hay que refrescar para que el sistema responda.
> > 3. Si vamos a "Pagos" veremos que el pago generado antes queda en Borrador.
> > 4. En "Recibos de Cliente" no podemos ingresar al recibo dado que da el error nuevamente.
> 
> ![image](https://user-images.githubusercontent.com/62858972/79994117-f0977600-848b-11ea-960e-eb04080eb827.png)

Hola. Estoy configurando también Odoo 13 y tengo el mismo problema.

Gracias,

Alejandro.-

**Comment by morrillo** [comment]
Resuelto actualizando modulo l10n_ar_account_withholding
