### ISSUE TITLE
Problemas con modulo account_check v13

### ISSUE THREAD

**Issue by pabarrientos** [ctmil/odoo-argentina#2]
Buenas... luego de instalar el módulo account_check desaparece del menú la opción para listar y crear facturas de proveedores

Versión afectada: 13

Pasos para reproducir:
Facturación->Proveedores->Facturas(esta opción desaparece)

**Comment by pabarrientos** [comment]
Listo... solucionado con commit 86cff76

**Comment by morrillo** [comment]
Genial entonces
