### ISSUE TITLE
Error de validación de factura, problema con el formato de los datos cargados.

### ISSUE THREAD

**Issue by Pablossi** [ctmil/odoo-argentina#21]
Error de validación de factura, problema con el formato de los datos cargados.

Estoy intentando hacer una validación en Homologacion para una factura y recibo el mensaje:

"AFIP Validation Error. Falla SOAP soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 2182). ---> Input string was not in a correct format."

Por lo que dice, creo entender que es un problema con la cadena de valores que estoy enviando y que algo esta mal cargado, pero estoy buscando el archivo de respuesta xml con los datos devueltos por el proceso remoto y no los puedo ubicar.

¿Alguien sabe donde se alojan estos archivos o a que se debe esta error?.

Version affectada: Ubuntu 20.04.1 LTS + Odoo 13.0-20200723 (Versión Community)

**Comment by morrillo** [comment]
Cierro el issue porque o no configuraron correctamente el impuesto de IVA, o no cargaron correctamente el CUIT
