### ISSUE TITLE
Error al instalar l10n_ar_account_vat_ledger

### ISSUE THREAD

**Issue by josejachuf** [ctmil/odoo-argentina#25]
Cuando intento instalar el módulo sobre la versión 13.0 se produce el siguiente error:

**El campo `digital_agip_filename` no existe**

Tengo todas las dependencias instaladas y actualizadas
El error completo es:

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 392, in _check_xml
>     self.postprocess_and_fields(view.model, view_doc, view.id)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 984, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 612, in raise_view_error
>     raise ValueError(message)
> ValueError: El campo `digital_agip_filename` no existe
> 
> Contexto del error:
> Vista `Account VAT Ledger AGIP`
> [view_id: 1303, xml_id: n/a, model: account.vat.ledger, parent_id: 1297]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 712, in parse
>     self._tag_root(de)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 674, in _tag_root
>     f(rec)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 674, in _tag_root
>     f(rec)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 577, in _tag_record
>     record = model._load_records([data], self.mode == 'update')
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 4080, in _load_records
>     records = self._load_records_create([data['values'] for data in to_create])
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3994, in _load_records_create
>     return self.create(values)
>   File "<decorator-gen-32>", line 2, in create
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 336, in _model_create_multi
>     return create(self, arg)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 473, in create
>     return super(View, self).create(vals_list)
>   File "<decorator-gen-3>", line 2, in create
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 336, in _model_create_multi
>     return create(self, arg)
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3775, in create
>     fields[0].determine_inverse(batch_recs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/fields.py", line 1114, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
>     view.write(data)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 491, in write
>     res = super(View, self).write(self._compute_defaults(vals))
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3564, in write
>     real_recs._validate_fields(set(vals) - set(inverse_fields))
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 1176, in _validate_fields
>     check(self)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
>     raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
> odoo.exceptions.ValidationError: ('Error while validating view\n\nEl campo `digital_agip_filename` no existe\n\nContexto del error:\nVista `Account VAT Ledger AGIP`\n[view_id: 1303, xml_id: n/a, model: account.vat.ledger, parent_id: 1297]', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 625, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 311, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/pycompat.py", line 14, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 670, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 351, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/service/model.py", line 93, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 340, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 916, in __call__
>     return self.method(*args, **kw)
>   File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 516, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1326, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 387, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 374, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-60>", line 2, in button_immediate_install
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/usr/local/lib/python3.7/site-packages/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 423, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 315, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 225, in load_module_graph
>     load_data(cr, idref, mode, kind='data', package=package, report=report)
>   File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 68, in load_data
>     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 736, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 803, in convert_xml_import
>     obj.parse(doc.getroot())
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 721, in parse
>     exc_info[2]
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/pycompat.py", line 13, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 712, in parse
>     self._tag_root(de)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 674, in _tag_root
>     f(rec)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 674, in _tag_root
>     f(rec)
>   File "/usr/local/lib/python3.7/site-packages/odoo/tools/convert.py", line 577, in _tag_record
>     record = model._load_records([data], self.mode == 'update')
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 4080, in _load_records
>     records = self._load_records_create([data['values'] for data in to_create])
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3994, in _load_records_create
>     return self.create(values)
>   File "<decorator-gen-32>", line 2, in create
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 336, in _model_create_multi
>     return create(self, arg)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 473, in create
>     return super(View, self).create(vals_list)
>   File "<decorator-gen-3>", line 2, in create
>   File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 336, in _model_create_multi
>     return create(self, arg)
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3775, in create
>     fields[0].determine_inverse(batch_recs)
>   File "/usr/local/lib/python3.7/site-packages/odoo/fields.py", line 1114, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
>     view.write(data)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 491, in write
>     res = super(View, self).write(self._compute_defaults(vals))
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 3564, in write
>     real_recs._validate_fields(set(vals) - set(inverse_fields))
>   File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 1176, in _validate_fields
>     check(self)
>   File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
>     raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
> odoo.tools.convert.ParseError: "Error while validating view
> 
> El campo `digital_agip_filename` no existe
> 
> Contexto del error:
> Vista `Account VAT Ledger AGIP`
> [view_id: 1303, xml_id: n/a, model: account.vat.ledger, parent_id: 1297]
> None" while parsing /usr/home/odoo/addons/odoo-argentina/l10n_ar_account_agipinfo/views/account_vat_report_view.xml:2, near
> <odoo>
>     <data>
>         <record model="ir.ui.view" id="account_vat_ledger_agipform">
>             <field name="name">Account VAT Ledger AGIP</field> 
>             <field name="model">account.vat.ledger</field>
>             <field name="inherit_id" ref="l10n_ar_account_vat_ledger.account_vat_ledger_form"/>
>             <field name="arch" type="xml">
>                 
>                 <notebook>
>                     <page string="AGIP" name="agip">
>                         <button name="compute_agip_data" type="object" string="Generar Informacion" states="draft"/>
>                         <group>
>                             <field name="digital_agip_filename" invisible="1"/>
>                             <group>
>                                 <field name="digital_agip_file" filename="digital_vouchers_filename"/>
>                             </group>
>                         </group>
>                         <group col="1" groups="base.group_no_one">
>                             
>                             <field name="REGAGIP_CV_CBTE"/>
>                         </group>
>                     </page>
>                 </notebook>
>             </field>
>         </record>          
>     </data>
> </odoo>

**Comment by morrillo** [comment]
Hice un update al l10n_ar_account_agip_info, ahora deberia funcionar

**Comment by josejachuf** [comment]
Gracias Gustavo. Ahora puede instalarlo (l10n_ar_account_vat_ledger)
Soy muy nuevo en odoo (2° día). Entiendo que este módulo da soporte a los libros de IVA y luego de instalado debería tener acceso desde el menú Facturación ->Informes, cosa que no estoy viendo.
Probé instalar este l10n_ar_account_agip_info y tira el mismo error:
ValueError: El campo `digital_agip_filename` no existe
