### ISSUE TITLE
l10n_ar_sale_additional_taxes depende de account_check pero no lo dice en el manifest

### ISSUE THREAD

**Issue by cebas** [ctmil/odoo-argentina#26]
Estoy usando el odoo 13 de este repo. Cuando intento instalar l10n_ar_sale_additional_taxes, me da este error: **TypeError: Model 'account.check' does not exist in registry.**

En models.py de l10n_ar_sale_additional_taxes, AccountCheck hereda de account.check y como no tengo instalado el módulo account_check, no encuentra ese modelo.

account_check debería ser una dependencia de l10n_ar_sale_additional_taxes

**Comment by mariogustavoorrillo** [comment]
Esta resuelto en la versión 14.0
