### ISSUE TITLE
Modulo Gastos. Los pagos con empresas deben crearse desde grupos de pagos

### ISSUE THREAD

**Issue by gbhadolfo** [ctmil/odoo-argentina#28]
> ** Los pagos con empresas deben crearse desde grupos de pagos.**
>
> *Version affectada:*
> 
>  - 13
> 
> *Pasos para reproducir:*
> 
>  Cuando se quiere pagar un gasto (app Gastos), ya sea a reembolsar o pagado por la comañía.
> 
> *Lo que pasa actualmente:*
> 
>  -  Mensaje con Los pagos con empresas deben crearse desde grupos de pagos
> 
> *Lo que debe pasar:*
> 
>  - Que lleve a la pantalla de payment group o que haga el pago sin usar payment group.
>

**Comment by morrillo** [comment]
es discutible... porque no necesariamente es buena idea en Argentina ingresar los gastos precisamente en el modulo de gastos (por temas impositivos). Si queres mandame un mail a gustavo.orrillo@moldeointeractive.com.ar y lo discutimos

**Comment by davidmonterocrespo24** [comment]
Hola, también tengo problemas con el mensaje "Modulo Gastos. Los pagos con empresas deben crearse desde grupos de pagos" con un módulo de pagos. Quería saber si esta validación es importante para el correcto funcionamiento de los pagos?


![image](https://user-images.githubusercontent.com/47928504/128439013-59cbca93-bb08-4045-a0dc-1d71f0bdec21.png)
