### ISSUE TITLE
TypeError: data must be bytes or None, not str

### ISSUE THREAD

**Issue by crishtorres** [ctmil/odoo-argentina#31]
> **TypeError: data must be bytes or None, not str**
>
> *Version affectada:*
> 
>  - 13.0
> 
> *Pasos para reproducir:*
> 
>  1. Generar certificado
>  2. En diarios, generar uno Ventas (según video)
>  3. Al presionar "Dummy Test" o cualquiera de las opciones
> 
> *Lo que pasa actualmente:*
> 
>  - Da el mensaje TypeError: data must be bytes or None, not str
> 
> *Lo que debe pasar:*
> 
>  - Conectar! 
>
> *Analisis profunda:*
>
>  - Intente varias soluciones, problemas de dependencias y demas, pero no logro dar con la solución. Todo en Homologación.

**Comment by mariogustavoorrillo** [comment]
Es un problema de instalación de M2Crypto o pyafipws.
