### ISSUE TITLE
No calcula impuestos en factura de compra

### ISSUE THREAD

**Issue by barct** [ctmil/odoo-argentina#33]
Cuando cargo una factura de proveedor no se calculan los impuestos en la sección 
Apuntes Contables - > Account Move
Esto hace que luego el reporte IVA Compras no se calcule bien.

*Versión afectada 13.0*

*Pasos para reproducir:*
Para Responsables inscriptos
1) Cargar factura de proveedor (Factura A)
2) Cargar items con impuestos
3) Hacer click en calcular impuestos tampoco hace nada.
![img1](https://user-images.githubusercontent.com/23461656/100685387-0abb0000-335b-11eb-9522-9752fcbde684.png)
![img2](https://user-images.githubusercontent.com/23461656/100685391-0b539680-335b-11eb-807a-686c0c6634e4.png)

Entiendo que debería calcular como lo hace con la factura de venta.
En la seccion Apuntes Contables - > Account Move deberían aparecer los impuestos calculados

**Comment by franconicolau** [comment]
Hola @barct , pudiste resolver este issue?
Pude replicar el mismo error, estuve viendo la funcion del codigo "compute_taxes()" y no logre identificar ninguna inconsistencia pero aun asi no agrega los impuestos.
Muchas gracias. Saludos
Franco

**Comment by barct** [comment]
no, no he logrado saber la causa

**Comment by mariogustavoorrillo** [comment]
El boton "Computar Impuestos" solo se usa en las facturas de compra. Y se lo usa para las percepciones. Si cargan una factura de compra y no se computa el impuesto, es un problema de configuración.
