### ISSUE TITLE
certificado expirado

### ISSUE THREAD

**Issue by lucasdamianmartino** [ctmil/odoo-argentina#39]
Hola,
Creería que instalé todo correctamente pero al hacer el dummy test me muestra este resultado:
afip1 odoo.http: ('No se puede conectar. Esto es lo que recibimos: ns1:cms.cert.expired: Certificado expirado', '') 

Estoy haciendo las pruebas de homologacion con los certificados DEMO.
Estos exipiraron o estoy haciendo algo mal?
Muchas gracias y es una genialidad lo que hicieron!

**Comment by Garridus** [comment]
Me pasó lo mismo hoy haciendo pruebas. Ya lo había instalado y funcionaba bien.

**Comment by ibuioli** [comment]
Hola! Lo del certificado Expirado no tiene que ver con la localización sino con AFIP, cada X tiempo expiran y hay que volver a emitirlos. Si tienen un contador disponible les puede dar una mano, sino en la página de AFIP están las instrucciones.

**Comment by Garridus** [comment]
Hola. Yo me refiero al certificado del  demo.

**Comment by ibuioli** [comment]
El certificado de demo lo liberó AdHoc para hacer pruebas hace más de 1 año y ya hace rato que venció. Hay que dar de alta uno con un CUIT. Saludos.
