### ISSUE TITLE
Localizacion Argentina como Monotributista

### ISSUE THREAD

**Issue by Pablossi** [ctmil/odoo-argentina#50]
Estoy intentando configurar la localización Argentino como Monotributistas en la versión 14

Anteriormente hice pruebas con Odoo 13 en homologación y funcionaba con credenciales propias de homologación. Traía el numero de CAE, pero decidí instalar la versión 14 con la idea de ponerlo en producción. Asi que genere nuevos certificados de producción pero no consigo publicar la factura y obtener el numero de CAE.

Estoy intentando presentar la factura en producción a "Consumidor Final Anónimo", puse el parámetro 
afip.ws.env.type en "production" y cree las secuencias para las facturas C y para las notas de crédito.

No creo que sea un problema del modulo en si mismo pero busco algún mensaje de error en el LOG y no encuentro nada.

Alguna idea de que puede estar pasando?

**Comment by gustavoorrillo** [comment]
Pablo, los issues son para indicar errores. Si no hay error, si tenes un problema de configuración, no es el lugar.

**Comment by mariogustavoorrillo** [comment]
Pablo, es un tema de soporte. No es un problema de la localización. Por lo pronto te recomendaria que el plan de cuentas sea de responsable inscripto. Por otra parte, el plan de cuentas no lo instala ninguno de estos módulos.
