### ISSUE TITLE
No aparece la opción para crear Año Fiscal

### ISSUE THREAD

**Issue by diegonoia** [ctmil/odoo-argentina#53]
Hola, estoy en la versión 15.0 CE con la localización argentina con facturación electrónica  instalada. Tengo seleccionado el plan de cuentas para responsable inscripto, hasta acá todo bien.  El tema es que cuando quiero crear el AÑO FISCAL, no me aparece la opción. Busque en los tutoriales y en la documentación y veo que esta en Facturación/Contabilidad ->Configuración -> Ajustes, pero no me aparece la opción. El módulo l10n_ar esta instalado.

**Comment by mariogustavoorrillo** [comment]
Los periodos fiscales no estan disponibles en Odoo desde al menos la versión 10

**Comment by diegonoia** [comment]
Gracias Gustavo, entiendo que te referís a la versión CE. Por lo cual no
hay manera de tener un año fiscal ni llevar un balance?

Estaba leyendo esto, que no es la versión CE claramente.
https://www.odoo.com/documentation/15.0/es/applications/finance/accounting/taxation/fiscal_year/fiscal_year.html

**Comment by mariogustavoorrillo** [comment]
No es un issue de la localización. Cualquier duda mandala a la lista

https://groups.google.com/g/odoo-argentina?pli=1
