### ISSUE TITLE
Error de dependencia, al instalar l10n_ar_account_vat_ledger.

### ISSUE THREAD

**Issue by LucioBisiach** [ctmil/odoo-argentina#7]
Version afectada:
- 13.0

Pasos para reproducir:
- Al instalar el modulo "l10n_ar_account_vat_ledge", informa un error que dice lo siguiente:

"Intenta isntalar el modulo 'l10n_ar_account_vat_ledger' que depende del módulo 'l10_ar_account'. Este ultimo módulo no esta disponible en sus sistema.

**Comment by morrillo** [comment]
Se solucionó al remover el viejo módulo l10n_ar_account_vat_ledger_citi
