### ISSUE TITLE
Estado de la localizacion en odoo 13.0 (no calcula los campos para registrar en AFIP WSFE)

### ISSUE THREAD

**Issue by cgnunezbantics** [ctmil/odoo-argentina#8]
Hola. Estoy probando odoo y quería probarlo con la localización Argentina.
La verdad estoy un poco confundido, vi algunos artículos donde parecía que la localización Argentina ya se estaban usando en odoo 13. Por lo que veo este repo https://github.com/ctmil/odoo-argentina parece de moldeo forkeado del de adhoc. Probe este, lo pude instalar y configurar algunas cosas, comunicarlo con Afip, peor a la hora de registrar la factura, parece que no estar completa la parte de los impuestos. No dan los calculos del importe de la factura. No se si faltan modulos o no se llego a completar. Me podrás orientar como es la situación para saber donde podemos aportar? Desde ya muchas gracias.

**Comment by morrillo** [comment]
1) github se usa para issues
2) para consultas generales esta la lista de odoo-argentina y el grupo de whatsapp
3) en caso que necesites ayuda nuestra, vendemos la consultoría sobre como usar el módulo
de vuelta... no planteaste un issue asi que voy cerrandolo

**Comment by cgnunezbantics** [comment]
Ok @morrillo , ahora te genero un issue con el detalle del error.
Genial, cual es la lista de odoo-argentina y el grupo de whatsapp?
Muchas Gracias.
