### ISSUE TITLE
Error al validar factura en Afip

### ISSUE THREAD

**Issue by cgnunezbantics** [ctmil/odoo-argentina#9]
Las pruebas las realize con odoo 13 de fuentes de odoo oficiales.
Se instalaron los siguientes modulos:
l10n_ar
l10n_ar_afipws
l10n_ar_afipws_fe
l10n_ar_bank
sale_management

Se configuro lo básico y los certificados de afip en homologacion. La comunicación con Afip funciono bien. (servicio Dummy y GetPuntosVenta)
Se genera una factura con importe total 1488.30 y 258.30 de IVA 21 %  y al tocar el botón publicar, devuelve el siguiente error:

```
AFIP Validation Error. 10048: El campo  'Importe Total' ImpTotal, debe ser igual  a la  suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10018: Si ImpIva es mayor a 0 el objeto Iva y AlicIva son obligatorios.
10024: Si ImpTrib es mayor a 0 el objeto Tributos y Tributo son obligatorios.
```

Se observa en el objeto XML que envio, que no se llenaron adecuadamente los campos que afip requiere.
```
<FECAESolicitar xmlns="http://ar.gov.afip.dif.FEV1/">
    <Auth><Token>11111</Token><Sign>2222</Sign>
<Cuit>200000001</Cuit></Auth><FeCAEReq><FeCabReq><CantReg>1</CantReg><PtoVta>19</PtoVta><CbteTipo>1</CbteTipo></FeCabReq><FeDetReq><FECAEDetRequest><Concepto>1</Concepto><DocTipo>80</DocTipo><DocNro>200000001</DocNro><CbteDesde>1</CbteDesde><CbteHasta>1</CbteHasta><CbteFch>20200130</CbteFch><ImpTotal>1488.30</ImpTotal><ImpTotConc>0.00</ImpTotConc><ImpNeto>0.00</ImpNeto><ImpOpEx>0.00</ImpOpEx><ImpTrib>258.30</ImpTrib><ImpIVA>258.30</ImpIVA><MonId>PES</MonId><MonCotiz>1.0</MonCotiz></FECAEDetRequest></FeDetReq></FeCAEReq></FECAESolicitar>
```

Aguardo sus comentarios. Gracias

**Comment by morrillo** [comment]
esta mal configurado, mira en este video que se indica como configurar


https://www.moldeointeractive.com.ar/blog/moldeo-interactive-1/post/webinar-de-localizacion-argentina-en-odoo-13-community-747
cierro el issue
